### PR TITLE
Lms 7.9.2 pre20191202 perl 5.30.1

### PR DESCRIPTION
**Pull request by lmiphay**
Hi Stuart / @hickinbottoms 

Here is a 7.9.2 pre-release version with support for perl 5.30.1 which has just been stabilised.

Also this is useful link for anyone upgrading perl versions: https://wiki.gentoo.org/wiki/Perl#Upgrading_.28major_version.29

Thanks,

Paul

### CODE REVIEW

**Comment by hickinbottoms** [comment]
Will take a look -- many thanks for that. Your PR's are always easy to review.

**Comment by Motorpsycho123** [comment]
Any progress here soon?

**Comment by hickinbottoms** [comment]
> Any progress here soon?
Apologies -- yes will look in the next few days (dropped off my radar).

**Comment by hickinbottoms** [comment]
Merged (via --squash to ensure signed-off-by requirements met)
Many thanks for the PR, Paul.

**Pull request closed without merging**
