### PR TITLE
add ebuild for the full 7.9.0 release version (and perl 5.24)

### PR DESCRIPTION
**Pull request by lmiphay**
Here is an updated ebuild for the full 7.9.0 release made back in March:
http://forums.slimdevices.com/showthread.php?107110-Logitech-Media-Server-7-9-is-out!

I have only used this for about a day without any problems, and so other peoples experiences would be interesting to hear (my test env: openrc/per5.24/amd64, SBR/jivelite only).

Note that I installed this on top of @user7466 pre20160918 build from pr #10

Other changes:

1. perl 5.24 is the only perl supported
2. EAPI 6
3. Dropped ~x86 (no shared libraries from upstream?)
4. Reworked QA_PREBUILT/src_prepare to avoid listing the so's and bin's (see point 1)
5. Added a pointer in pkg_postinst to the support thread on the forums
6. Switched to openrc-run (see pr #8 )
7. Removed the EnvironmentFile in the service file to avoid a systemd QA warning (it should be pointed to a systemd specific file under /etc/logitechmediaserver)

### CODE REVIEW

**Comment by user7466** [comment]
I've updated to this ebuild and it is working great for me so far, thanks so much!

**Comment by schmerg** [comment]
It's working fine for me too, thanks, and very timely as portage was getting very keen to update my perl to 5.24 which I've now been able to complete (usual gentoo perl upgrade fancy footwork notwithstanding).

**Comment by lmiphay** [comment]
This pull request collided with Stuart adding a logitechmediaserver-bin-7.9.0 ebuild to the overlay.

If you have an problem using this ebuild, it would be best to reinstall using the overlay version,  and if you still have the problem, then create an issue and we can work from there. 

If you don't have any issues, then there should be no need to reinstall.

@hickinbottoms do you want any of the changes in this pull request? or will we just close it?

**Comment by hickinbottoms** [comment]
Sorry I hadn't noticed this. I've checked through this PR and I think there are a couple of things I'll pull in, but it'll be easier for me to make those manually rather than pick through the merge conflicts.

The things I'll manually add are:

1. Simple copyright bump
2. Update, the init script to use "openrc-run"
3. ebuild updates.

I'll make those myself and push an update soon, but it should be materially the same as this PR.

Thanks again -- I need to get my notification settings sorted out for github so I don't miss these PRs...

**Pull request closed without merging**
