### PR TITLE
jivelite ebuild - 13 Dec 2014 snapshot

### PR DESCRIPTION
**Pull request by lmiphay**
Hi Stuart,

Here is an ebuild for jivelite - a nice controller application which compliments squeezelite.

If you start it from a terminal, it is quite chatty describing in detail what it gets up to. This includes some WARN and ERROR messages, but they don't appear to impact the actual operation of the app as far as I can tell.

Paul
snapshot1

### CODE REVIEW

**Comment by hickinbottoms** [comment]
Lovely -- I'll take a look at that.
I've not been keeping a close eye on the LMS scene for a while, so I'd not even heard of this, which is a little embarrassing.

**Comment by hickinbottoms** [comment]
Thanks for that. I can build it OK, but I don't have any way to test it (or, at least, I've not managed to get it to show the GUI in a KVM VM). I've pushed it out to the overlay. Many thanks.

**Comment by lmiphay** [comment]
Ok thanks for doing that.

That's a pity (no GUI) - is there any error message on the console where you start jivelite?

I wonder if it might be a missing dependency - I now have it running nicely on two bare metal pc's - including the visualiser feed from squeezelite.

Paul

**Comment by lmiphay** [comment]
For comparison purposes here is the full chatter I see from startup until the GUI appears:
```
$ jivelite

JiveLite 0.1.0
20150816 20:31:23.764 INFO   jivelite - JiveMain.lua:267 JiveLite version 0.1.0
20150816 20:31:23.768 INFO   jivelite.ui.draw - jiveL_initSDL:205 6400,1600 32 bits/pixel 4 bytes/pixel [R<<16 G<<8 B<<0]
20150816 20:31:23.768 INFO   jivelite.ui.draw - jiveL_initSDL:206 Hardware acceleration is not available
20150816 20:31:23.768 INFO   jivelite.ui.draw - jiveL_initSDL:207 Window manager is available
20150816 20:31:23.794 INFO   jivelite.applets - AppletManager.lua:92 User Path: /home/lmiphay/.jivelite/userpath
20150816 20:31:23.810 INFO   jivelite.applets - AppletManager.lua:318 Registering: DesktopJive
20150816 20:31:23.810 INFO   jivelite.applets - AppletManager.lua:318 Registering: BlankScreenSaver
20150816 20:31:23.812 INFO   jivelite.applets - AppletManager.lua:318 Registering: ChooseMusicSource
20150816 20:31:23.813 INFO   jivelite.applets - AppletManager.lua:318 Registering: CustomizeHomeMenu
20150816 20:31:23.813 INFO   jivelite.applets - AppletManager.lua:318 Registering: DemoApplet
20150816 20:31:23.813 INFO   jivelite.applets - AppletManager.lua:318 Registering: HDGridSkin
20150816 20:31:23.813 INFO   jivelite.applets - AppletManager.lua:318 Registering: HDSkin
20150816 20:31:23.814 INFO   jivelite.applets - AppletManager.lua:318 Registering: HttpAuth
20150816 20:31:23.816 INFO   jivelite.applets - AppletManager.lua:318 Registering: ImageViewer
20150816 20:31:23.817 INFO   jivelite.applets - AppletManager.lua:318 Registering: JogglerSkin
20150816 20:31:23.817 INFO   jivelite.applets - AppletManager.lua:318 Registering: LogSettings
20150816 20:31:23.818 INFO   jivelite.applets - AppletManager.lua:318 Registering: NowPlaying
20150816 20:31:23.818 INFO   jivelite.applets - AppletManager.lua:318 Registering: Quit
20150816 20:31:23.819 INFO   jivelite.applets - AppletManager.lua:318 Registering: ScreenSavers
20150816 20:31:23.819 INFO   jivelite.applets - AppletManager.lua:318 Registering: SelectPlayer
20150816 20:31:23.820 INFO   jivelite.applets - AppletManager.lua:318 Registering: SelectSkin
20150816 20:31:23.821 INFO   jivelite.applets - AppletManager.lua:318 Registering: SetupAppletInstaller
20150816 20:31:23.821 INFO   jivelite.applets - AppletManager.lua:318 Registering: SetupDateTime
20150816 20:31:23.821 INFO   jivelite.applets - AppletManager.lua:318 Registering: SetupLanguage
20150816 20:31:23.822 INFO   jivelite.applets - AppletManager.lua:318 Registering: SetupWallpaper
20150816 20:31:23.822 INFO   jivelite.applets - AppletManager.lua:318 Registering: SetupWelcome
20150816 20:31:23.823 INFO   jivelite.applets - AppletManager.lua:318 Registering: SlimBrowser
20150816 20:31:23.829 INFO   jivelite.applets - AppletManager.lua:318 Registering: SlimDiscovery
20150816 20:31:23.829 INFO   jivelite.applets - AppletManager.lua:318 Registering: SlimMenus
20150816 20:31:23.831 INFO   jivelite.applets - AppletManager.lua:318 Registering: WQVGAgridSkin
20150816 20:31:23.831 INFO   jivelite.applets - AppletManager.lua:318 Registering: WQVGAsmallSkin
20150816 20:31:23.834 INFO   jivelite - JiveMain.lua:591 select skin: WQVGAsmallSkin
20150816 20:31:23.863 INFO   jivelite.applets - AppletManager.lua:709 store settings: SetupAppletInstaller
20150816 20:31:23.864 INFO   applet.SlimDiscovery - SlimDiscoveryApplet.lua:580 selected nur
20150816 20:31:23.864 INFO   applet.SlimMenus - SlimMenusApplet.lua:1170 SlimMenusApplet:notify_playerCurrent(Player {nur})
20150816 20:31:23.864 INFO   applet.SlimMenus - SlimMenusApplet.lua:1202 player changed from:false to Player {nur} but server not yet present
20150816 20:31:23.864 INFO   applet.SlimMenus - SlimMenusApplet.lua:1238 No server, Fetching initial server, SlimServer {sakc1}
20150816 20:31:23.902 INFO   squeezebox.server - SlimServer.lua:752 connected nur
20150816 20:31:23.905 INFO   squeezebox.server - SlimServer.lua:764 self.mac being set to---->nil
20150816 20:31:23.910 INFO   squeezebox.server - SlimServer.lua:752 connected kulb
20150816 20:31:23.911 INFO   squeezebox.server - SlimServer.lua:752 connected sakc1
20150816 20:31:23.912 INFO   squeezebox.server - SlimServer.lua:764 self.mac being set to---->nil
20150816 20:31:23.913 INFO   squeezebox.server - SlimServer.lua:764 self.mac being set to---->9e:b5:a5:88:64:17
20150816 20:31:23.951 INFO   jivelite.applets - AppletManager.lua:709 store settings: SlimDiscovery
20150816 20:31:23.951 INFO   applet.SlimDiscovery - SlimDiscoveryApplet.lua:465 notify_playerPower: true
20150816 20:31:23.951 INFO   applet.SlimDiscovery - SlimDiscoveryApplet.lua:401 connected nur
20150816 20:31:23.951 INFO   applet.SlimMenus - SlimMenusApplet.lua:1170 SlimMenusApplet:notify_playerCurrent(LocalPlayer {nur})
20150816 20:31:23.951 INFO   applet.SlimMenus - SlimMenusApplet.lua:1253 player changed from:false to LocalPlayer {nur} for server: SlimServer {sakc1} from server: SlimServer {sakc1}
20150816 20:31:23.951 INFO   applet.SlimMenus - SlimMenusApplet.lua:1261 
Subscribing to /slim/menustatus/
74:d0:2b:c6:ad:16
20150816 20:31:23.992 INFO   applet.SlimMenus - SlimMenusApplet.lua:503 _menuSink(63) SlimServer {sakc1} menuDirective: nil isCurrentServer:true
20150816 20:31:23.992 INFO   applet.SlimMenus - SlimMenusApplet.lua:638 Eliminated myMusic node from server, since now handled locally
20150816 20:31:23.997 INFO   jivelite.applets - AppletManager.lua:709 store settings: ImageViewer
20150816 20:31:23.997 INFO   applet.SlimMenus - SlimMenusApplet.lua:808 hiding any 'connecting to server' popup after menu response from current server, SlimServer {sakc1}
20150816 20:31:24.000 INFO   applet.ChooseMusicSource - ChooseMusicSourceApplet.lua:543 Hiding popup, exists?: nil
20150816 20:31:24.024 INFO   applet.NowPlaying - NowPlayingApplet.lua:399 notify_playerDigitalVolumeControl: 1
20150816 20:31:24.024 INFO   applet.SlimBrowser - SlimBrowserApplet.lua:3770 notify_playerDigitalVolumeControl()1

```

**Comment by hickinbottoms** [comment]
It's slightly more disappointing for me, I just see:
JiveLite 0.1.0 20150816 20:39:36.872 INFO   jivelite - 
JiveMain.lua:267 JiveLite version 0.1.0 20150816 20:39:36.872 
ERROR  jivelite.ui.draw - jiveL_initSDL:198 SDL_Init(V|T|A): No 
available video device

This is on the console of a VM that doesn't have X installed, 
running as root. I'm pretty sure it's either because it's in a VM, 
or somethign else (SDL, lua etc) isn't built with the right flags. 
I'm not too worried about it.

Stuart



Paul Healy <notifications@github.com> writes:

> For comparison purposes here is the full chatter I see from 
> startup until the GUI appears:
>
> $ jivelite
>
> JiveLite 0.1.0 20150816 20:31:23.764 INFO   jivelite - 
> JiveMain.lua:267 JiveLite version 0.1.0 20150816 20:31:23.768 
> INFO   jivelite.ui.draw - jiveL_initSDL:205 6400,1600 32 
> bits/pixel 4 bytes/pixel [R<<16 G<<8 B<<0] 20150816 20:31:23.768 
> INFO   jivelite.ui.draw - jiveL_initSDL:206 Hardware 
> acceleration is not available 20150816 20:31:23.768 INFO 
> jivelite.ui.draw - jiveL_initSDL:207 Window manager is available 
> 20150816 20:31:23.794 INFO   jivelite.applets - 
> AppletManager.lua:92 User Path: /home/lmiphay/.jivelite/userpath 
> 20150816 20:31:23.810 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: DesktopJive 20150816 
> 20:31:23.810 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: BlankScreenSaver 20150816 20:31:23.812 INFO 
> jivelite.applets - AppletManager.lua:318 Registering: 
> ChooseMusicSource 20150816 20:31:23.813 INFO   jivelite.applets 
> - AppletManager.lua:318 Registering: CustomizeHomeMenu 20150816 
> 20:31:23.813 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: DemoApplet 20150816 20:31:23.813 INFO 
> jivelite.applets - AppletManager.lua:318 Registering: HDGridSkin 
> 20150816 20:31:23.813 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: HDSkin 20150816 20:31:23.814 
> INFO   jivelite.applets - AppletManager.lua:318 Registering: 
> HttpAuth 20150816 20:31:23.816 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: ImageViewer 20150816 
> 20:31:23.817 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: JogglerSkin 20150816 20:31:23.817 INFO 
> jivelite.applets - AppletManager.lua:318 Registering: 
> LogSettings 20150816 20:31:23.818 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: NowPlaying 20150816 
> 20:31:23.818 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: Quit 20150816 20:31:23.819 INFO   jivelite.applets 
> - AppletManager.lua:318 Registering: ScreenSavers 20150816 
> 20:31:23.819 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: SelectPlayer 20150816 20:31:23.820 INFO 
> jivelite.applets - AppletManager.lua:318 Registering: SelectSkin 
> 20150816 20:31:23.821 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: SetupAppletInstaller 20150816 
> 20:31:23.821 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: SetupDateTime 20150816 20:31:23.821 INFO 
> jivelite.applets - AppletManager.lua:318 Registering: 
> SetupLanguage 20150816 20:31:23.822 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: SetupWallpaper 20150816 
> 20:31:23.822 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: SetupWelcome 20150816 20:31:23.823 INFO 
> jivelite.applets - AppletManager.lua:318 Registering: 
> SlimBrowser 20150816 20:31:23.829 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: SlimDiscovery 20150816 
> 20:31:23.829 INFO   jivelite.applets - AppletManager.lua:318 
> Registering: SlimMenus 20150816 20:31:23.831 INFO 
> jivelite.applets - AppletManager.lua:318 Registering: 
> WQVGAgridSkin 20150816 20:31:23.831 INFO   jivelite.applets - 
> AppletManager.lua:318 Registering: WQVGAsmallSkin 20150816 
> 20:31:23.834 INFO   jivelite - JiveMain.lua:591 select skin: 
> WQVGAsmallSkin 20150816 20:31:23.863 INFO   jivelite.applets - 
> AppletManager.lua:709 store settings: SetupAppletInstaller 
> 20150816 20:31:23.864 INFO   applet.SlimDiscovery - 
> SlimDiscoveryApplet.lua:580 selected nur 20150816 20:31:23.864 
> INFO   applet.SlimMenus - SlimMenusApplet.lua:1170 
> SlimMenusApplet:notify_playerCurrent(Player {nur}) 20150816 
> 20:31:23.864 INFO   applet.SlimMenus - SlimMenusApplet.lua:1202 
> player changed from:false to Player {nur} but server not yet 
> present 20150816 20:31:23.864 INFO   applet.SlimMenus - 
> SlimMenusApplet.lua:1238 No server, Fetching initial server, 
> SlimServer {sakc1} 20150816 20:31:23.902 INFO 
> squeezebox.server - SlimServer.lua:752 connected nur 20150816 
> 20:31:23.905 INFO   squeezebox.server - SlimServer.lua:764 
> self.mac being set to---->nil 20150816 20:31:23.910 INFO 
> squeezebox.server - SlimServer.lua:752 connected kulb 20150816 
> 20:31:23.911 INFO   squeezebox.server - SlimServer.lua:752 
> connected sakc1 20150816 20:31:23.912 INFO   squeezebox.server - 
> SlimServer.lua:764 self.mac being set to---->nil 20150816 
> 20:31:23.913 INFO   squeezebox.server - SlimServer.lua:764 
> self.mac being set to---->9e:b5:a5:88:64:17 20150816 
> 20:31:23.951 INFO   jivelite.applets - AppletManager.lua:709 
> store settings: SlimDiscovery 20150816 20:31:23.951 INFO 
> applet.SlimDiscovery - SlimDiscoveryApplet.lua:465 
> notify_playerPower: true 20150816 20:31:23.951 INFO 
> applet.SlimDiscovery - SlimDiscoveryApplet.lua:401 connected nur 
> 20150816 20:31:23.951 INFO   applet.SlimMenus - 
> SlimMenusApplet.lua:1170 
> SlimMenusApplet:notify_playerCurrent(LocalPlayer {nur}) 20150816 
> 20:31:23.951 INFO   applet.SlimMenus - SlimMenusApplet.lua:1253 
> player changed from:false to LocalPlayer {nur} for server: 
> SlimServer {sakc1} from server: SlimServer {sakc1} 20150816 
> 20:31:23.951 INFO   applet.SlimMenus - SlimMenusApplet.lua:1261 
> Subscribing to /slim/menustatus/ 74:d0:2b:c6:ad:16 20150816 
> 20:31:23.992 INFO   applet.SlimMenus - SlimMenusApplet.lua:503 
> _menuSink(63) SlimServer {sakc1} menuDirective: nil 
> isCurrentServer:true 20150816 20:31:23.992 INFO 
> applet.SlimMenus - SlimMenusApplet.lua:638 Eliminated myMusic 
> node from server, since now handled locally 20150816 
> 20:31:23.997 INFO   jivelite.applets - AppletManager.lua:709 
> store settings: ImageViewer 20150816 20:31:23.997 INFO 
> applet.SlimMenus - SlimMenusApplet.lua:808 hiding any 
> 'connecting to server' popup after menu response from current 
> server, SlimServer {sakc1} 20150816 20:31:24.000 INFO 
> applet.ChooseMusicSource - ChooseMusicSourceApplet.lua:543 
> Hiding popup, exists?: nil 20150816 20:31:24.024 INFO 
> applet.NowPlaying - NowPlayingApplet.lua:399 
> notify_playerDigitalVolumeControl: 1 20150816 20:31:24.024 INFO 
> applet.SlimBrowser - SlimBrowserApplet.lua:3770 
> notify_playerDigitalVolumeControl()1
>
> — Reply to this email directly or view it on GitHub.

--
stuart@hickinbottom.com

**Comment by lmiphay** [comment]
Ok that sounds like media-libs/libsdl hasn't been built with the right set of use flags - this is what I have:
```
$  equery uses media-libs/libsdl
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for media-libs/libsdl-1.2.15-r8:
 U I
 + + X             : Add support for X11
 - - aalib         : Add support for media-libs/aalib (ASCII-Graphics Library)
 - - abi_x86_32    : 32-bit (x86) libraries
 + + alsa          : Add support for media-libs/alsa-lib (Advanced Linux Sound
                     Architecture)
 - - custom-cflags : Build with user-specified CFLAGS (unsupported)
 - - dga           : Add DGA (Direct Graphic Access) support for X
 - - fbcon         : Add framebuffer support for the console, via the kernel
 + + joystick      : Control joystick support (disable at your own risk)
 - - libcaca       : Add support for colored ASCII-art graphics
 - - nas           : Add support for network audio sound
 + + opengl        : Add support for OpenGL (3D graphics)
 - - oss           : Add support for OSS (Open Sound System)
 + + pulseaudio    : Add support for PulseAudio sound server
 + + sound         : Control audio support (disable at your own risk)
 - - static-libs   : Build static versions of dynamic libraries as well
 - - tslib         : Build with tslib support for touchscreen devices
 + + video         : Control video support (disable at your own risk)
 + + xinerama      : Add support for the xinerama X11 extension, which is
                     mandatory if you work in multiple monitors setup
 + + xv            : Add in optional support for the Xvideo extension (an X API
                     for video playback)

```
From your description, my guess would be the 'X' use flag?

P.

**Comment by hickinbottoms** [comment]
Yes, that was it. My test VM doesn't have X so, after a bit of emerging, that seems to work.
I've noticed that media-libs/sdl-image needs to be build with the 'png' flag or jivelite cannot load the wallpapers, so I'll add that use flag dependency to a small bump to the ebuild.
Thanks a lot for the ebuild and help.

**Pull request merged**
